# Generated by Django 5.2.6 on 2025-09-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbenefit',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='contact_instagram',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='contact_linkedin',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='contact_whatsapp',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='event_status',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='venue_google_map_link',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='venue_location',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='58F5085D', max_length=8, unique=True),
        ),
    ]
