# Generated by Django 5.2.6 on 2025-09-20 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsubmission',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='projectsubmission',
            old_name='title',
            new_name='project_title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Participant', 'Participant'), ('Volunteer', 'Volunteer'), ('Technical Support', 'Technical Support'), ('Technical Lead', 'Technical Lead'), ('Lead Organizer', 'Lead Organizer'), ('Event Manager', 'Event Manager')], default='Participant', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='led_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
