# Generated by Django 5.2.6 on 2025-09-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_eventbenefit_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='A670C0FF', max_length=8, unique=True),
        ),
    ]
