# Generated by Django 5.2.6 on 2025-09-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_event_event_status_alter_team_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='F633B36C', max_length=8, unique=True),
        ),
    ]
