# Generated by Django 5.2.6 on 2025-09-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_team_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='B5849416', max_length=8, unique=True),
        ),
    ]
