# Generated by Django 5.2.6 on 2025-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_event_event_start_alter_team_team_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbenefit',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='event_end',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='event_mode',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='event_start',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='registration_end',
        ),
        migrations.RemoveField(
            model_name='eventbenefit',
            name='registration_start',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_mode',
            field=models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='physical', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='20C92D78', max_length=8, unique=True),
        ),
    ]
